
import React, { useRef, useState, useEffect } from 'react';
import { AppSettings } from '../../types';
import { useTranslation } from '../../hooks/useTranslation';

interface UserManualProps {
    settings: AppSettings;
}

export const UserManual: React.FC<UserManualProps> = ({ settings }) => {
    const contentRef = useRef<HTMLDivElement>(null);
    const { t } = useTranslation(settings.language);
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    const handlePrint = () => {
        if (!contentRef.current) return;
        const printWindow = window.open('', '_blank');
        if (!printWindow) return;

        printWindow.document.write(`
            <html>
            <head>
                <title>${t('manual_title')}</title>
                <style>
                    body { font-family: 'Segoe UI', sans-serif; padding: 40px; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; }
                    h1 { color: #2563eb; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; }
                    h2 { margin-top: 40px; color: #1e293b; border-left: 5px solid #2563eb; padding-left: 15px; font-size: 22px; }
                    h3 { margin-top: 30px; color: #475569; font-size: 18px; }
                    h4 { margin-top: 20px; font-size: 16px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; font-weight: bold; }
                    p { margin-bottom: 15px; text-align: justify; }
                    ul, ol { margin-bottom: 20px; padding-left: 25px; }
                    li { margin-bottom: 8px; }
                    .toc { background: #f8fafc; padding: 25px; border-radius: 8px; border: 1px solid #e2e8f0; margin-bottom: 40px; }
                    .toc-title { font-weight: bold; font-size: 18px; margin-bottom: 15px; border-bottom: 1px solid #cbd5e1; padding-bottom: 5px; }
                    .toc-item { margin-bottom: 8px; color: #2563eb; text-decoration: none; cursor: pointer; }
                    .toc-item:hover { text-decoration: underline; }
                    
                    /* Print Specifics */
                    @media print {
                        body { padding: 0; }
                        .no-print { display: none; }
                        h2 { page-break-before: always; margin-top: 20px; }
                        h2:first-of-type { page-break-before: avoid; }
                    }
                </style>
            </head>
            <body>
                <h1>${t('manual_title')}</h1>
                <p style="color: #666; font-size: 18px;">${t('manual_subtitle')}</p>
                
                <div class="toc">
                    <div class="toc-title">${t('manual_toc')}</div>
                    <div class="toc-item">1. ${t('manual_intro_title')}</div>
                    <div class="toc-item">2. ${t('manual_dashboard_title')}</div>
                    <div class="toc-item">3. ${t('manual_services_title')}</div>
                    <div class="toc-item">4. ${t('manual_ai_title')}</div>
                    <div class="toc-item">5. ${t('manual_fleet_title')}</div>
                    <div class="toc-item">6. ${t('manual_financials_title')}</div>
                    <div class="toc-item">7. ${t('manual_settings_title')}</div>
                </div>
                
                <div id="intro"><h2>1. ${t('manual_intro_title')}</h2>${t('manual_intro_content')}</div>
                <div id="dashboard"><h2>2. ${t('manual_dashboard_title')}</h2>${t('manual_dashboard_content')}</div>
                <div id="services"><h2>3. ${t('manual_services_title')}</h2>${t('manual_services_content')}</div>
                <div id="ai"><h2>4. ${t('manual_ai_title')}</h2>${t('manual_ai_content')}</div>
                <div id="fleet"><h2>5. ${t('manual_fleet_title')}</h2>${t('manual_fleet_content')}</div>
                <div id="financials"><h2>6. ${t('manual_financials_title')}</h2>${t('manual_financials_content')}</div>
                <div id="settings"><h2>7. ${t('manual_settings_title')}</h2>${t('manual_settings_content')}</div>
                
                <div style="margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; text-align: center; font-size: 12px; color: #999;">
                    Generated by NCC Application. &copy; ${new Date().getFullYear()}
                </div>
            </body>
            </html>
        `);
        printWindow.document.close();
    };

    const scrollToSection = (id: string) => {
        const element = document.getElementById(id);
        if (element) {
            element.scrollIntoView({ behavior: 'smooth' });
        }
    };

    if (!mounted) return null;

    return (
        <div className="h-full flex flex-col bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-200 font-sans">
            <div className="flex-shrink-0 sticky top-0 bg-white/95 dark:bg-slate-900/95 backdrop-blur-sm border-b border-slate-200 dark:border-slate-700 py-4 px-4 sm:px-8 flex justify-between items-center z-20 shadow-sm">
                <div>
                    <h1 className="text-xl sm:text-2xl font-bold">{t('manual_title')}</h1>
                    <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 hidden sm:block">{t('manual_subtitle')}</p>
                </div>
                <div className="flex gap-3">
                    <button onClick={handlePrint} className="flex items-center px-4 py-2 sm:px-5 sm:py-2.5 bg-blue-600 text-white font-semibold rounded-lg shadow-md hover:bg-blue-700 transition-all text-sm">
                        <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                        Print / PDF
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-4 sm:p-8 scroll-smooth">
                <div className="max-w-4xl mx-auto pb-20" ref={contentRef}>
                    
                    {/* Table of Contents */}
                    <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-xl border border-slate-200 dark:border-slate-700 mb-12">
                        <h3 className="text-lg font-bold mb-4 border-b border-slate-200 dark:border-slate-700 pb-2 text-slate-800 dark:text-slate-100">{t('manual_toc')}</h3>
                        <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3 text-sm">
                            {['intro', 'dashboard', 'services', 'ai', 'fleet', 'financials', 'settings'].map((section, idx) => (
                                <li key={section}>
                                    <button onClick={() => scrollToSection(section)} className="text-blue-600 dark:text-blue-400 hover:underline text-left font-medium flex items-center">
                                        <span className="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 w-6 h-6 flex items-center justify-center rounded-full text-xs mr-3 font-bold">{idx + 1}</span>
                                        {t(`manual_${section}_title` as any)}
                                    </button>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Sections */}
                    <div className="space-y-16 prose prose-slate dark:prose-invert max-w-none prose-headings:scroll-mt-24">
                        <section id="intro">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">1. {t('manual_intro_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_intro_content') }} />
                        </section>

                        <section id="dashboard">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">2. {t('manual_dashboard_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_dashboard_content') }} />
                        </section>

                        <section id="services">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">3. {t('manual_services_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_services_content') }} />
                        </section>

                        <section id="ai">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">4. {t('manual_ai_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_ai_content') }} />
                        </section>

                        <section id="fleet">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">5. {t('manual_fleet_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_fleet_content') }} />
                        </section>

                        <section id="financials">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">6. {t('manual_financials_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_financials_content') }} />
                        </section>

                        <section id="settings">
                            <h2 className="text-3xl font-bold text-slate-800 dark:text-slate-100 border-b border-slate-200 dark:border-slate-700 pb-2 mb-6">7. {t('manual_settings_title')}</h2>
                            <div dangerouslySetInnerHTML={{ __html: t('manual_settings_content') }} />
                        </section>
                    </div>

                    <div className="mt-20 pt-8 border-t border-slate-200 dark:border-slate-700 text-center text-slate-400 text-sm">
                        &copy; {new Date().getFullYear()} {settings.companyName || 'New ChAIffeur Calendar'}. <br/>
                        <span className="text-xs opacity-70">Documentation generated automatically.</span>
                    </div>
                </div>
            </div>
        </div>
    );
};
